import Head from 'next/head'
import { Inter } from 'next/font/google'
import Intro from '@/components/Intro'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title> Peanuts API </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Intro/>
      </main>

    </>
  )
}
